version: "3.9"
services:
  app:
    build: .
    expose: 
      - "5000"
  balancer:
    image: dockercloud/haproxy
    links: 
        - app
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
# networks:
  # default:
    # Use a custom driver
    # driver: custom-driver-1
    